//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenrePlaylist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenrePlaylist()
        {
            this.GenrePlaylists1 = new HashSet<GenrePlaylist>();
            this.Tracks = new HashSet<Track>();
        }
    
        public int GenrePlaylist_ID { get; set; }
        public string ImagePath { get; set; }
        public string Genre { get; set; }
        public Nullable<int> GenrePlaylist_GenrePlaylist_ID { get; set; }
        public Nullable<int> Track_Track_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenrePlaylist> GenrePlaylists1 { get; set; }
        public virtual GenrePlaylist GenrePlaylist1 { get; set; }
        public virtual Track Track { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
