//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.Singers = new HashSet<Singer>();
            this.Tracks1 = new HashSet<Track>();
        }
    
        public int Track_ID { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int Album_ID { get; set; }
        public int TotalListens { get; set; }
        public bool Verification { get; set; }
        public Nullable<int> Track_Track_ID { get; set; }
        public Nullable<int> Playlist_Playlist_ID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Playlist Playlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Singer> Singers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track> Tracks1 { get; set; }
        public virtual Track Track1 { get; set; }
    }
}
