//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationCode
    {
        public int Code_ID { get; set; }
        public string Code { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<int> Sender_User_ID { get; set; }
    
        public virtual User Sender { get; set; }
    }
}
